Fix android build: Shared library compiles zig code
Previously, when building for android, these steps were followed:

1. build the app static library: which contains the main business logic
2. build the sokol static library: which contains the app framework and graphics apis (basically the engine)
3. link them together into one dynamic library to be loaded in by NativeActivity.

This ended up causing link errors due to invalid relocations on step 3
```
error: ld.lld: relocation R_AARCH64_TLSLE_ADD_TPREL_HI12 against debug.panic_stage cannot be used with -shared
    note: defined in /Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a(/Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a.o)
    note: referenced by debug.zig:399 (/Users/george/bin/lib/std/debug.zig:399)
    note:               /Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a.o:(debug.panicImpl) in archive /Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a
```

Turns out its because you cant just link to static archives together and get a valid shared library out of it. Something got lost in step 1. This commit fixes the android build by compiling the app code (step 1) and creating the shared library together. So the steps now look like this

1. build the sokol static library
2. build the app code into a shared library and link in the sokol static library.

I'm not sure why this works but the other process isn't. But ill take it i guess.